import { useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import {
  Activity, AlertCircle, ArrowLeft, ArrowUpRight, BarChart3, BookOpen,
  BrainCircuit, Check, ChevronRight, CircleDot, ClipboardList, Clock3,
  CloudUpload, FileCode2, FileSearch, Fingerprint, FolderKanban, Gauge,
  Globe2, Hash, Inbox, KeyRound, LayoutDashboard, ListFilter, Mail,
  Menu, Network, Plus, RefreshCw, Search, Settings2, ShieldAlert, ShieldCheck,
  SlidersHorizontal, Sparkles, Terminal, Upload, X, XCircle
} from 'lucide-react';
import {
  getGetDashboardActivityQueryKey, getGetDashboardStatsQueryKey,
  getGetEmailQueryKey, getGetEmailStatusQueryKey, getListEmailsQueryKey,
  getListInvestigationsQueryKey, useAnalyzeEmail, useCreateInvestigation,
  useCreateReport, useGetDashboardActivity, useGetDashboardStats, useGetEmail,
  useGetEmailAuthentication, useGetEmailDomains, useGetEmailGeolocation,
  useGetEmailGraph, useGetEmailHeaders, useGetEmailIps, useGetEmailRelayTrace,
  useGetEmailStatus, useGetEmailUrls, useListEmails, useListInvestigations,
  useUploadEmail, useUpdateInvestigation
} from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';

const nav = [
  { href: '/', label: 'Overview', icon: LayoutDashboard },
  { href: '/scan', label: 'Scan email', icon: FileSearch },
  { href: '/emails', label: 'Email evidence', icon: Inbox },
  { href: '/investigations', label: 'Investigations', icon: FolderKanban },
  { href: '/reports', label: 'Reports', icon: ClipboardList },
];

const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Unavailable';
const formatShort = (value?: string | null) => value ? new Date(value).toLocaleDateString([], { month: 'short', day: 'numeric' }) : '—';
const titleCase = (value?: string | null) => value ? value.replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase()) : 'Unavailable';
const riskTone = (score?: number | null) => score == null ? 'neutral' : score >= 70 ? 'critical' : score >= 40 ? 'warning' : 'clear';
const toneClass = (tone: string) => tone === 'critical' ? 'text-red-300 bg-red-400/10 border-red-400/25' : tone === 'warning' ? 'text-amber-300 bg-amber-400/10 border-amber-400/25' : tone === 'clear' ? 'text-primary bg-primary/10 border-primary/25' : 'text-muted-foreground bg-muted/40 border-border';

function StatusPill({ value, score }: { value?: string | null; score?: number | null }) {
  const tone = riskTone(score);
  return <span data-testid="status-analysis" className={cn('inline-flex items-center gap-1.5 border px-2 py-1 text-[10px] font-bold uppercase tracking-[.14em]', toneClass(tone))}>
    <span className="h-1.5 w-1.5 rounded-full bg-current" />{titleCase(value || tone)}
  </span>;
}

function LoadingRows({ count = 4 }: { count?: number }) {
  return <div className="space-y-2" data-testid="loading-state">{Array.from({ length: count }).map((_, i) => <div key={i} className="h-14 animate-pulse rounded border border-border bg-muted/30" />)}</div>;
}

function QueryError({ onRetry, label = 'The evidence service is unavailable.' }: { onRetry?: () => void; label?: string }) {
  return <div className="flex items-center justify-between gap-4 rounded border border-red-400/25 bg-red-400/5 p-4 text-sm text-red-200" data-testid="error-state">
    <span className="flex items-center gap-2"><AlertCircle className="h-4 w-4" />{label}</span>
    {onRetry && <Button onClick={onRetry} variant="outline" size="sm" data-testid="button-retry"><RefreshCw className="h-3.5 w-3.5" />Retry</Button>}
  </div>;
}

function EmptyState({ icon: Icon = Inbox, title, detail, action }: { icon?: typeof Inbox; title: string; detail: string; action?: React.ReactNode }) {
  return <div className="flex min-h-48 flex-col items-center justify-center border border-dashed border-border bg-card/40 p-8 text-center" data-testid="empty-state">
    <Icon className="mb-3 h-8 w-8 text-muted-foreground/60" />
    <h3 className="font-semibold text-foreground">{title}</h3>
    <p className="mt-1 max-w-sm text-sm text-muted-foreground">{detail}</p>
    {action && <div className="mt-5">{action}</div>}
  </div>;
}

function Shell({ children }: { children: React.ReactNode }) {
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  return <div className="min-h-[100dvh] bg-background text-foreground">
    <aside className={cn('fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-sidebar-border bg-sidebar px-4 py-5 transition-transform md:translate-x-0', open ? 'translate-x-0' : '-translate-x-full')}>
      <div className="mb-9 flex items-center gap-3 px-2">
        <div className="grid h-9 w-9 place-items-center bg-primary text-primary-foreground"><Fingerprint className="h-5 w-5" /></div>
        <div><div className="font-mono text-[13px] font-medium tracking-tight text-sidebar-foreground">MAILTRACE</div><div className="font-mono text-[9px] uppercase tracking-[.22em] text-primary">AI / FORENSICS</div></div>
      </div>
      <div className="mb-3 px-2 font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Workspace</div>
      <nav className="space-y-1">{nav.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} data-testid={`link-nav-${label.toLowerCase().replace(' ', '-')}`} className={cn('group flex items-center gap-3 border-l-2 px-3 py-2.5 text-sm', location === href ? 'border-primary bg-sidebar-accent text-sidebar-foreground' : 'border-transparent text-sidebar-foreground/65 hover:border-sidebar-primary/40 hover:bg-sidebar-accent/70 hover:text-sidebar-foreground')}><Icon className={cn('h-4 w-4', location === href && 'text-primary')} /><span>{label}</span>{location === href && <ChevronRight className="ml-auto h-3 w-3 text-primary" />}</Link>)}</nav>
      <div className="mt-auto space-y-4">
        <div className="border border-sidebar-border bg-sidebar-accent/50 p-3"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Live API</div><p className="mt-2 text-xs leading-relaxed text-sidebar-foreground/60">Evidence is sourced from your connected analysis service.</p></div>
        <Link href="/settings" data-testid="link-settings" className="flex items-center gap-3 px-3 py-2 text-sm text-sidebar-foreground/65 hover:text-sidebar-foreground"><Settings2 className="h-4 w-4" />Settings</Link>
        <div className="flex items-center gap-3 border-t border-sidebar-border px-2 pt-4"><div className="grid h-8 w-8 place-items-center rounded-full bg-secondary text-xs font-bold text-primary">AR</div><div><div className="text-xs font-semibold text-sidebar-foreground">Analyst workspace</div><div className="font-mono text-[9px] text-muted-foreground">LOCAL SESSION</div></div></div>
      </div>
    </aside>
    {open && <button aria-label="Close menu" className="fixed inset-0 z-20 bg-background/70 md:hidden" onClick={() => setOpen(false)} data-testid="button-close-menu" />}
    <main className="min-h-[100dvh] md:pl-64">
      <header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur md:px-8">
        <button className="mr-3 text-muted-foreground md:hidden" onClick={() => setOpen(true)} data-testid="button-open-menu"><Menu className="h-5 w-5" /></button>
        <div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="font-mono text-primary">CASE ROOM</span><span>/</span><span>{nav.find((n) => n.href === location)?.label || 'MailTrace'}</span></div>
        <div className="flex items-center gap-3"><span className="hidden items-center gap-2 font-mono text-[10px] text-muted-foreground sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-primary" />SERVICE CONNECTED</span><Link href="/scan" data-testid="link-header-scan"><Button size="sm"><Upload className="h-3.5 w-3.5" />Upload evidence</Button></Link></div>
      </header>
      <div className="mx-auto max-w-[1440px] p-5 md:p-8">{children}</div>
    </main>
  </div>;
}

function PageIntro({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) {
  return <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] font-medium uppercase tracking-[.2em] text-primary"><span className="h-px w-5 bg-primary" />{eyebrow}</div><h1 className="text-3xl font-extrabold tracking-[-.04em] text-foreground md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{detail}</p></div>{action}</div>;
}

export function DashboardPage() {
  const stats = useGetDashboardStats();
  const activity = useGetDashboardActivity();
  const emails = useListEmails({ limit: 6 });
  return <Shell><PageIntro eyebrow="Operational overview" title="Evidence room" detail="A live view of stored email analyses, active risk, and the latest analyst activity." action={<Link href="/scan" data-testid="link-start-scan"><Button><CloudUpload className="h-4 w-4" />Start a scan</Button></Link>} />
    {stats.isLoading ? <LoadingRows count={1} /> : stats.isError ? <QueryError onRetry={() => stats.refetch()} /> : stats.data ? <div className="mb-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Analyses stored', stats.data.totalEmails, Mail], ['High-risk messages', stats.data.highRiskEmails, ShieldAlert], ['Open investigations', stats.data.openInvestigations, FolderKanban], ['Extracted indicators', stats.data.extractedIndicators, Fingerprint]].map(([label, value, Icon]: [string, number, typeof Mail]) => <Card key={label} className="border-border bg-card/70"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground">{label}</span><Icon className="h-4 w-4 text-primary/80" /></div><div className="text-3xl font-extrabold tracking-tight">{value}</div><div className="mt-2 flex items-center gap-1.5 font-mono text-[10px] text-muted-foreground"><Activity className="h-3 w-3 text-primary" />Updated {formatDate(stats.data.lastUpdated)}</div></CardContent></Card>)}</div> : null}
    <div className="grid gap-5 xl:grid-cols-[1.4fr_.9fr]">
      <Card className="border-border bg-card/70"><CardHeader className="flex-row items-center justify-between border-b border-border px-5 py-4"><div><CardTitle className="text-base">Recent evidence</CardTitle><p className="mt-1 text-xs text-muted-foreground">Latest records from the analysis store</p></div><Link href="/emails" data-testid="link-all-emails" className="flex items-center gap-1 font-mono text-[10px] uppercase tracking-wider text-primary">View all <ArrowUpRight className="h-3 w-3" /></Link></CardHeader><CardContent className="p-0">{emails.isLoading ? <div className="p-5"><LoadingRows /></div> : emails.isError ? <div className="p-5"><QueryError onRetry={() => emails.refetch()} /></div> : emails.data?.length ? <div>{emails.data.map((email) => <Link href={`/emails/${email.id}`} key={email.id} data-testid={`row-email-${email.id}`} className="flex items-center gap-4 border-b border-border px-5 py-4 transition-colors hover:bg-muted/30"><div className="hidden h-9 w-9 place-items-center border border-border bg-muted/30 sm:grid"><Mail className="h-4 w-4 text-muted-foreground" /></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{email.subject || '(no subject)'}</div><div className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{email.sender}</div></div><div className="hidden text-right sm:block"><div className="font-mono text-[10px] text-muted-foreground">{formatShort(email.receivedAt)}</div><div className="mt-1 text-[10px] text-muted-foreground">{titleCase(email.threatType)}</div></div><StatusPill value={email.analysisStatus} score={email.riskScore} /><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link>)}</div> : <EmptyState title="No email evidence yet" detail="Upload a real message to create your first traceable record." action={<Link href="/scan"><Button size="sm"><Upload className="h-4 w-4" />Upload an email</Button></Link>} />}</CardContent></Card>
      <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Activity stream</CardTitle><p className="mt-1 text-xs text-muted-foreground">Events from the live workspace</p></CardHeader><CardContent className="p-5">{activity.isLoading ? <LoadingRows count={4} /> : activity.isError ? <QueryError onRetry={() => activity.refetch()} /> : activity.data?.length ? <div className="space-y-5">{activity.data.map((item) => <div key={item.id} className="relative flex gap-3" data-testid={`activity-${item.id}`}><div className={cn('mt-1 h-2 w-2 shrink-0 rounded-full', item.tone === 'critical' ? 'bg-red-400' : item.tone === 'warning' ? 'bg-amber-300' : 'bg-primary')} /><div className="min-w-0"><div className="text-sm font-medium">{item.label}</div><div className="mt-0.5 text-xs text-muted-foreground">{item.detail}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground/70">{formatDate(item.timestamp)}</div></div></div>)}</div> : <EmptyState icon={Activity} title="No activity recorded" detail="Workspace events will appear here as real analyses complete." />}</CardContent></Card>
    </div>
  </Shell>;
}

export function ScanPage() {
  const upload = useUploadEmail();
  const [, setLocation] = useLocation();
  const [file, setFile] = useState<File | null>(null);
  const [dragging, setDragging] = useState(false);
  const choose = (next: File | undefined) => { if (next && /\.(eml|msg|txt)$/i.test(next.name)) setFile(next); };
  const submit = () => { if (file) upload.mutate({ data: file }, { onSuccess: (email) => setLocation(`/emails/${email.id}`) }); };
  return <Shell><PageIntro eyebrow="Evidence intake" title="Scan an email" detail="Upload an original .eml, .msg, or .txt file. MailTrace stores the source record and attaches every derived result to its provenance." />
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <Card className="border-border bg-card/70"><CardContent className="p-5 md:p-8"><div onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); choose(e.dataTransfer.files[0]); }} className={cn('trace-grid flex min-h-[330px] flex-col items-center justify-center border border-dashed p-8 text-center', dragging ? 'border-primary bg-primary/5' : 'border-border')} data-testid="dropzone-upload"><div className="mb-5 grid h-16 w-16 place-items-center border border-primary/30 bg-primary/10 text-primary"><CloudUpload className="h-7 w-7" /></div><h2 className="text-xl font-bold">Drop original evidence here</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">Files stay connected to their analysis record. Do not upload a screenshot or copied body if you need defensible headers.</p><label className="mt-6 cursor-pointer"><input type="file" accept=".eml,.msg,.txt" className="sr-only" onChange={(e) => choose(e.target.files?.[0])} data-testid="input-email-file" /><span className="inline-flex min-h-9 items-center gap-2 border border-border bg-secondary px-4 py-2 text-sm font-medium hover:bg-muted"><FileCode2 className="h-4 w-4" />Choose a file</span></label>{file && <div className="mt-6 flex items-center gap-3 border border-primary/30 bg-primary/5 px-4 py-3 text-left" data-testid="selected-file"><FileCode2 className="h-4 w-4 text-primary" /><div><div className="text-sm font-semibold">{file.name}</div><div className="font-mono text-[10px] text-muted-foreground">{(file.size / 1024).toFixed(1)} KB · Ready for intake</div></div><button onClick={() => setFile(null)} className="ml-3 text-muted-foreground hover:text-foreground" data-testid="button-clear-file"><X className="h-4 w-4" /></button></div>}</div>{upload.isError && <div className="mt-4"><QueryError label="Upload failed. The original file was not stored." /></div>}<div className="mt-5 flex justify-end"><Button disabled={!file || upload.isPending} onClick={submit} data-testid="button-upload-email">{upload.isPending ? <><RefreshCw className="h-4 w-4 animate-spin" />Uploading evidence</> : <><Upload className="h-4 w-4" />Upload and analyze</>}</Button></div></CardContent></Card>
      <div className="space-y-5"><Card className="border-border bg-card/70"><CardHeader className="px-5 py-4"><CardTitle className="text-sm">What gets preserved</CardTitle></CardHeader><CardContent className="space-y-4 px-5 pb-5">{[['Source hash', 'SHA-256 of the uploaded bytes'], ['Headers', 'Original routing and authentication fields'], ['Indicators', 'URLs, domains, IPs, and relay hops'], ['Findings', 'Evidence-backed analysis output']].map(([title, detail]) => <div key={title} className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><div><div className="text-sm font-semibold">{title}</div><div className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{detail}</div></div></div>)}</CardContent></Card><div className="border border-amber-300/20 bg-amber-300/5 p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-amber-200"><ShieldAlert className="h-4 w-4" />Analyst note</div><p className="mt-3 text-xs leading-relaxed text-amber-100/70">Only upload material you are authorized to investigate. A scan creates a persistent record visible to this workspace.</p></div></div>
    </div>
  </Shell>;
}

export function EmailsPage() {
  const [search, setSearch] = useState('');
  const emails = useListEmails({ search: search || undefined, limit: 100 });
  return <Shell><PageIntro eyebrow="Evidence index" title="Email evidence" detail="Search the stored analysis record. Every row below reflects data returned by the connected API." action={<Link href="/scan"><Button><Upload className="h-4 w-4" />Upload evidence</Button></Link>} />
    <Card className="border-border bg-card/70"><CardHeader className="gap-4 border-b border-border px-5 py-4 md:flex-row md:items-center md:justify-between"><div><CardTitle className="text-base">Analyzed messages</CardTitle><p className="mt-1 text-xs text-muted-foreground">{emails.data?.length ?? 0} records returned</p></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search subject or sender" className="pl-9" data-testid="input-search-emails" /></div></CardHeader><CardContent className="p-0">{emails.isLoading ? <div className="p-5"><LoadingRows count={6} /></div> : emails.isError ? <div className="p-5"><QueryError onRetry={() => emails.refetch()} /></div> : emails.data?.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-border bg-muted/20 font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground"><tr><th className="px-5 py-3">Message</th><th className="px-5 py-3">Received</th><th className="px-5 py-3">Threat</th><th className="px-5 py-3">Risk</th><th className="px-5 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody>{emails.data.map((email) => <tr key={email.id} className="border-b border-border/70 hover:bg-muted/20" data-testid={`row-evidence-${email.id}`}><td className="max-w-[360px] px-5 py-4"><div className="truncate font-semibold">{email.subject || '(no subject)'}</div><div className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{email.sender}</div></td><td className="whitespace-nowrap px-5 py-4 font-mono text-[10px] text-muted-foreground">{formatDate(email.receivedAt)}</td><td className="px-5 py-4 text-xs text-muted-foreground">{titleCase(email.threatType)}</td><td className="px-5 py-4 font-mono text-xs">{email.riskScore == null ? 'Unavailable' : `${email.riskScore}/100`}</td><td className="px-5 py-4"><StatusPill value={email.analysisStatus} score={email.riskScore} /></td><td className="px-5 py-4 text-right"><Link href={`/emails/${email.id}`} data-testid={`link-evidence-${email.id}`} className="inline-flex items-center gap-1 text-xs text-primary">Inspect <ArrowUpRight className="h-3 w-3" /></Link></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title={search ? 'No matching evidence' : 'No analyzed emails'} detail={search ? 'Try a different subject or sender.' : 'Upload a real email to begin an evidence-backed analysis.'} action={!search && <Link href="/scan"><Button size="sm">Upload an email</Button></Link>} /></div>}</CardContent></Card>
  </Shell>;
}

function ResultState({ loading, error, children, empty }: { loading?: boolean; error?: boolean; children: React.ReactNode; empty?: boolean }) {
  if (loading) return <LoadingRows count={2} />;
  if (error) return <QueryError />;
  if (empty) return <div className="py-5 text-center font-mono text-[10px] uppercase tracking-[.14em] text-muted-foreground">Unavailable / not configured</div>;
  return <>{children}</>;
}

function IndicatorList({ title, icon: Icon, data, valueKey = 'value' }: { title: string; icon: typeof Globe2; data?: Array<Record<string, unknown>>; valueKey?: string }) {
  return <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><Icon className="h-4 w-4 text-primary" />{title}<span className="ml-auto font-mono text-[10px] text-muted-foreground">{data?.length ?? 0}</span></CardTitle></CardHeader><CardContent className="p-0">{data?.length ? data.map((item, i) => <div key={`${String(item[valueKey])}-${i}`} className="border-b border-border/70 px-5 py-3"><div className="break-all font-mono text-xs">{String(item[valueKey])}</div><div className="mt-1 flex flex-wrap gap-2 font-mono text-[9px] uppercase tracking-wider text-muted-foreground"><span>{String(item.source || 'Source unavailable')}</span><span className="text-primary">{titleCase(String(item.status || 'unavailable'))}</span></div></div>) : <div className="p-5"><EmptyState icon={Icon} title={`No ${title.toLowerCase()} returned`} detail="The API returned no indicators for this record." /></div>}</CardContent></Card>;
}

export function EmailDetailPage() {
  const { id = '' } = useParams<{ id: string }>();
  const email = useGetEmail(id);
  const status = useGetEmailStatus(id);
  const headers = useGetEmailHeaders(id);
  const auth = useGetEmailAuthentication(id);
  const urls = useGetEmailUrls(id);
  const domains = useGetEmailDomains(id);
  const ips = useGetEmailIps(id);
  const relay = useGetEmailRelayTrace(id);
  const geo = useGetEmailGeolocation(id);
  const graph = useGetEmailGraph(id);
  const analyze = useAnalyzeEmail();
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<'summary' | 'headers' | 'body'>('summary');
  if (email.isLoading) return <Shell><LoadingRows count={5} /></Shell>;
  if (email.isError || !email.data) return <Shell><QueryError onRetry={() => email.refetch()} label="This email record could not be loaded." /></Shell>;
  const item = email.data;
  const findings = item.findings || [];
  return <Shell><div className="mb-5 flex items-center gap-3"><Link href="/emails" data-testid="link-back-emails" className="text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /></Link><span className="font-mono text-[10px] uppercase tracking-[.15em] text-muted-foreground">Evidence record / {id.slice(0, 12)}</span></div><div className="mb-7 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="min-w-0"><div className="mb-2 flex items-center gap-3"><StatusPill value={item.analysisStatus} score={item.riskScore} /><span className="font-mono text-[10px] text-muted-foreground">Captured {formatDate(item.createdAt)}</span></div><h1 className="max-w-4xl text-2xl font-extrabold tracking-[-.035em] md:text-3xl">{item.subject || '(no subject)'}</h1><p className="mt-2 font-mono text-xs text-muted-foreground">{item.sender} <span className="mx-2 text-primary">→</span> {item.recipient || 'Recipient unavailable'}</p></div><Button variant="outline" onClick={() => analyze.mutate({ id }, { onSuccess: (next) => queryClient.setQueryData(getGetEmailQueryKey(id), next) })} disabled={analyze.isPending} data-testid="button-reanalyze"><RefreshCw className={cn('h-4 w-4', analyze.isPending && 'animate-spin')} />{analyze.isPending ? 'Re-analyzing' : 'Re-run analysis'}</Button></div>
    <div className="mb-5 flex gap-1 overflow-x-auto border-b border-border">{[['summary', 'Findings & trace'], ['headers', 'Headers'], ['body', 'Message body']].map(([key, label]) => <button key={key} onClick={() => setTab(key as typeof tab)} data-testid={`tab-${key}`} className={cn('whitespace-nowrap border-b-2 px-4 py-3 text-xs font-semibold', tab === key ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground')}>{label}</button>)}</div>
    {tab === 'body' && <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-sm">Captured message body</CardTitle></CardHeader><CardContent className="max-h-[560px] overflow-auto p-5"><pre className="whitespace-pre-wrap font-mono text-xs leading-relaxed text-muted-foreground">{item.body || 'Message body unavailable.'}</pre></CardContent></Card>}
    {tab === 'headers' && <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-sm">Parsed header fields</CardTitle></CardHeader><CardContent className="p-0"><ResultState loading={headers.isLoading} error={headers.isError} empty={!headers.data?.length}>{headers.data?.map((h, i) => <div key={`${h.name}-${i}`} className="grid gap-2 border-b border-border/70 px-5 py-3 md:grid-cols-[180px_1fr]"><div className="font-mono text-[10px] font-bold uppercase tracking-wider text-primary">{h.name}</div><div className="break-all font-mono text-xs text-muted-foreground">{h.value}</div></div>)}</ResultState></CardContent></Card>}
    {tab === 'summary' && <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Card className="border-border bg-card/70"><CardContent className="p-5"><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Risk score</div><div className={cn('mt-2 text-4xl font-extrabold', riskTone(item.riskScore) === 'critical' ? 'text-red-300' : riskTone(item.riskScore) === 'warning' ? 'text-amber-300' : 'text-primary')}>{item.riskScore == null ? '—' : item.riskScore}</div><div className="mt-1 text-xs text-muted-foreground">Confidence {item.confidence == null ? 'unavailable' : `${item.confidence}%`}</div></CardContent></Card><Card className="border-border bg-card/70"><CardContent className="p-5"><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Threat classification</div><div className="mt-3 text-lg font-bold">{titleCase(item.threatType)}</div><div className="mt-1 text-xs text-muted-foreground">Classification returned by analysis</div></CardContent></Card><Card className="border-border bg-card/70"><CardContent className="p-5"><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Source fingerprint</div><div className="mt-3 truncate font-mono text-xs">{item.sha256 || 'Unavailable'}</div><div className="mt-2 text-xs text-muted-foreground">SHA-256</div></CardContent></Card></div>
      {status.data && status.data.progress < 100 && <div className="border border-primary/25 bg-primary/5 p-4"><div className="flex justify-between text-xs"><span className="font-semibold">Analysis in progress</span><span className="font-mono text-primary">{status.data.progress}%</span></div><div className="mt-3 h-1.5 bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${status.data.progress}%` }} /></div></div>}
      <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><ShieldAlert className="h-4 w-4 text-amber-300" />Findings <span className="ml-auto font-mono text-[10px] text-muted-foreground">{findings.length}</span></CardTitle></CardHeader><CardContent className="p-0">{findings.length ? findings.map((finding) => <div key={finding.id} className="border-b border-border/70 p-5"><div className="flex items-start justify-between gap-3"><div className="font-semibold">{finding.title}</div><span className={cn('border px-2 py-1 font-mono text-[9px] uppercase tracking-wider', toneClass(riskTone(finding.severity === 'critical' ? 80 : finding.severity === 'high' ? 70 : 30)))}>{finding.severity}</span></div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{finding.detail}</p><div className="mt-3 font-mono text-[10px] text-primary">Source: {finding.source}</div></div>) : <div className="p-5"><EmptyState icon={ShieldCheck} title="No findings returned" detail="No evidence-backed findings are attached to this record." /></div>}</CardContent></Card><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><KeyRound className="h-4 w-4 text-primary" />Authentication</CardTitle></CardHeader><CardContent className="p-5"><ResultState loading={auth.isLoading} error={auth.isError} empty={!auth.data}>{auth.data && <div className="space-y-3">{[['SPF', auth.data.spf], ['DKIM', auth.data.dkim], ['DMARC', auth.data.dmarc]].map(([name, value]) => <div key={name} className="flex items-center justify-between border-b border-border/70 pb-3"><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{name}</span><span className="flex items-center gap-2 text-xs font-semibold"><CircleDot className={cn('h-3.5 w-3.5', String(value).toLowerCase().includes('pass') ? 'text-primary' : 'text-amber-300')} />{String(value)}</span></div>)}<div className="pt-1 font-mono text-[10px] text-muted-foreground">Source: {auth.data.source}</div></div>}</ResultState></CardContent></Card></div>
      <div className="grid gap-5 xl:grid-cols-3"><IndicatorList title="URLs" icon={Globe2} data={urls.data as unknown as Array<Record<string, unknown>>} /><IndicatorList title="Domains" icon={Hash} data={domains.data as unknown as Array<Record<string, unknown>>} /><IndicatorList title="IP addresses" icon={Network} data={ips.data as unknown as Array<Record<string, unknown>>} /></div>
      <div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><Terminal className="h-4 w-4 text-primary" />Relay trace</CardTitle></CardHeader><CardContent className="p-5"><ResultState loading={relay.isLoading} error={relay.isError} empty={!relay.data?.length}>{relay.data && <div className="space-y-0">{relay.data.map((hop) => <div key={hop.position} className="flex gap-4"><div className="flex flex-col items-center"><div className="grid h-6 w-6 place-items-center rounded-full border border-primary/40 bg-primary/10 font-mono text-[9px] text-primary">{hop.position}</div><div className="h-8 w-px bg-border" /></div><div className="pb-4"><div className="font-mono text-xs">{hop.value}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-wider text-muted-foreground">{hop.source}</div></div></div>)}</div>}</ResultState></CardContent></Card><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><Network className="h-4 w-4 text-primary" />Threat graph</CardTitle></CardHeader><CardContent className="p-5"><ResultState loading={graph.isLoading} error={graph.isError} empty={!graph.data?.nodes?.length}>{graph.data && <div className="trace-grid min-h-40 border border-border p-4"><div className="flex flex-wrap gap-2">{graph.data.nodes.map((node) => <div key={node.id} className="border border-primary/30 bg-primary/10 px-2 py-1 font-mono text-[10px] text-primary">{node.label}</div>)}</div><div className="mt-5 font-mono text-[10px] text-muted-foreground">{graph.data.edges.length} relationship(s) returned from analysis</div></div>}</ResultState></CardContent></Card></div>
      <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="flex items-center gap-2 text-sm"><Globe2 className="h-4 w-4 text-primary" />Geolocation trace</CardTitle></CardHeader><CardContent className="p-5"><ResultState loading={geo.isLoading} error={geo.isError} empty={!geo.data?.length}>{geo.data && <div className="grid gap-3 md:grid-cols-3">{geo.data.map((point) => <div key={point.ip} className="border border-border bg-muted/20 p-3"><div className="font-mono text-xs text-primary">{point.ip}</div><div className="mt-2 text-sm">{[point.city, point.country].filter(Boolean).join(', ') || 'Location unavailable'}</div><div className="mt-1 font-mono text-[9px] text-muted-foreground">{point.source}</div></div>)}</div>}</ResultState></CardContent></Card>
    </div>}
  </Shell>;
}

export function InvestigationsPage() {
  const list = useListInvestigations();
  const create = useCreateInvestigation();
  const update = useUpdateInvestigation();
  const queryClient = useQueryClient();
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState('');
  const [notes, setNotes] = useState('');
  const [priority, setPriority] = useState('medium');
  const submit = () => { if (!title.trim()) return; create.mutate({ data: { title: title.trim(), notes, priority } }, { onSuccess: () => { setTitle(''); setNotes(''); setCreating(false); queryClient.invalidateQueries({ queryKey: getListInvestigationsQueryKey() }); } }); };
  return <Shell><PageIntro eyebrow="Case management" title="Investigations" detail="Persistent cases connect analyzed emails to an analyst-owned threat story." action={<Button onClick={() => setCreating((v) => !v)} data-testid="button-new-investigation"><Plus className="h-4 w-4" />New investigation</Button>} />
    {creating && <Card className="mb-5 border-primary/30 bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-sm">Create investigation</CardTitle></CardHeader><CardContent className="grid gap-4 p-5 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><label className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Case title</label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Suspected credential harvest" data-testid="input-investigation-title" /></div><div className="space-y-2"><label className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Priority</label><select value={priority} onChange={(e) => setPriority(e.target.value)} className="h-9 w-full border border-input bg-background px-3 text-sm" data-testid="select-investigation-priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></div><div className="space-y-2 md:col-span-2"><label className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Working notes</label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Document the investigation hypothesis and next steps." data-testid="input-investigation-notes" /></div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={() => setCreating(false)} data-testid="button-cancel-investigation">Cancel</Button><Button disabled={!title.trim() || create.isPending} onClick={submit} data-testid="button-create-investigation">{create.isPending ? 'Creating' : 'Create case'}</Button></div></CardContent></Card>}
    <Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Case register</CardTitle></CardHeader><CardContent className="p-0">{list.isLoading ? <div className="p-5"><LoadingRows count={4} /></div> : list.isError ? <div className="p-5"><QueryError onRetry={() => list.refetch()} /></div> : list.data?.length ? <div>{list.data.map((item) => <div key={item.id} className="flex flex-col gap-4 border-b border-border/70 p-5 md:flex-row md:items-center" data-testid={`row-investigation-${item.id}`}><div className="grid h-10 w-10 shrink-0 place-items-center border border-primary/25 bg-primary/10"><FolderKanban className="h-4 w-4 text-primary" /></div><div className="min-w-0 flex-1"><div className="font-semibold">{item.title}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{item.emailIds.length} linked email(s) · Updated {formatShort(item.updatedAt)}</div></div><div className="flex items-center gap-2"><span className="border border-border px-2 py-1 font-mono text-[9px] uppercase tracking-wider text-muted-foreground">{item.priority}</span><select value={item.status} onChange={(e) => update.mutate({ id: item.id, data: { status: e.target.value } }, { onSuccess: () => queryClient.invalidateQueries({ queryKey: getListInvestigationsQueryKey() }) })} className="h-8 border border-input bg-background px-2 text-xs" data-testid={`select-status-${item.id}`}><option value="open">Open</option><option value="in_progress">In progress</option><option value="closed">Closed</option></select></div></div>)}</div> : <div className="p-5"><EmptyState icon={FolderKanban} title="No investigations yet" detail="Create a case when an email needs sustained analyst attention." action={<Button size="sm" onClick={() => setCreating(true)}>Create an investigation</Button>} /></div>}</CardContent></Card>
  </Shell>;
}

export function ReportsPage() {
  const emails = useListEmails({ limit: 100 });
  const create = useCreateReport();
  const [selected, setSelected] = useState('');
  const [report, setReport] = useState<{ id: string; status: string; downloadUrl: string } | null>(null);
  return <Shell><PageIntro eyebrow="Defensible output" title="Reports" detail="Create a report from a stored email analysis. Report availability is always returned by the API; no local or simulated report is shown." />
    <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Create a report</CardTitle><p className="mt-1 text-xs text-muted-foreground">Select one analyzed email as the source record.</p></CardHeader><CardContent className="p-5">{emails.isLoading ? <LoadingRows /> : emails.isError ? <QueryError onRetry={() => emails.refetch()} /> : emails.data?.length ? <><label className="mb-2 block font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Source email</label><select value={selected} onChange={(e) => setSelected(e.target.value)} className="h-10 w-full border border-input bg-background px-3 text-sm" data-testid="select-report-email"><option value="">Choose an evidence record</option>{emails.data.map((email) => <option value={email.id} key={email.id}>{email.subject || '(no subject)'} · {email.sender}</option>)}</select><div className="mt-5 flex justify-end"><Button disabled={!selected || create.isPending} onClick={() => create.mutate({ data: { emailId: selected } }, { onSuccess: (next) => setReport(next) })} data-testid="button-create-report"><ClipboardList className="h-4 w-4" />{create.isPending ? 'Preparing report' : 'Create report'}</Button></div></> : <EmptyState icon={ClipboardList} title="No source emails available" detail="Create an analysis before requesting a report." />}</CardContent></Card><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Latest request</CardTitle></CardHeader><CardContent className="p-5">{report ? <div data-testid="report-result"><div className="flex items-center gap-2 text-primary"><Check className="h-4 w-4" /><span className="text-sm font-semibold">Report {titleCase(report.status)}</span></div><div className="mt-4 space-y-2 border-t border-border pt-4 font-mono text-[10px] text-muted-foreground"><div>REPORT ID <span className="float-right text-foreground">{report.id}</span></div><div>DOWNLOAD <span className="float-right text-foreground">{report.downloadUrl || 'Unavailable'}</span></div></div>{report.downloadUrl && <a href={report.downloadUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-xs text-primary" data-testid="link-download-report">Open report <ArrowUpRight className="h-3 w-3" /></a>}</div> : <EmptyState icon={ClipboardList} title="No report requested" detail="A report request will appear here after it is created by the API." />}</CardContent></Card></div>
  </Shell>;
}

export function SettingsPage() {
  const [saved, setSaved] = useState(false);
  const [density, setDensity] = useState('comfortable');
  return <Shell><PageIntro eyebrow="Workspace controls" title="Settings" detail="Review integration availability and set the display preferences for this analyst workspace." /><div className="grid gap-5 lg:grid-cols-2"><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Integrations</CardTitle><p className="mt-1 text-xs text-muted-foreground">Connection state is reported by the backend. Nothing here implies an unconfigured service is live.</p></CardHeader><CardContent className="space-y-4 p-5">{[['Analysis service', 'Required for parsing and findings', 'Connected', true], ['Reputation lookups', 'Optional indicator enrichment', 'Not configured', false], ['Geolocation provider', 'Optional relay location context', 'Not configured', false]].map(([name, detail, status, live]) => <div key={name as string} className="flex items-center gap-4 border-b border-border/70 pb-4 last:border-0 last:pb-0"><div className={cn('grid h-9 w-9 place-items-center border', live ? 'border-primary/30 bg-primary/10 text-primary' : 'border-border bg-muted/20 text-muted-foreground')}><KeyRound className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{name as string}</div><div className="mt-1 text-xs text-muted-foreground">{detail as string}</div></div><span className={cn('whitespace-nowrap font-mono text-[9px] uppercase tracking-wider', live ? 'text-primary' : 'text-muted-foreground')}>{status as string}</span></div>)}</CardContent></Card><Card className="border-border bg-card/70"><CardHeader className="border-b border-border px-5 py-4"><CardTitle className="text-base">Analyst preferences</CardTitle></CardHeader><CardContent className="space-y-5 p-5"><div><label className="mb-2 block font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Evidence list density</label><select value={density} onChange={(e) => { setDensity(e.target.value); setSaved(false); }} className="h-10 w-full border border-input bg-background px-3 text-sm" data-testid="select-density"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></div><div className="flex items-center justify-between border-t border-border pt-5"><div><div className="text-sm font-semibold">Local display preference</div><div className="mt-1 text-xs text-muted-foreground">Stored for this browser session only.</div></div><Button onClick={() => setSaved(true)} data-testid="button-save-settings">{saved ? <><Check className="h-4 w-4" />Saved</> : 'Save preference'}</Button></div></CardContent></Card></div></Shell>;
}